name: 'Automatic Release Creation'
description: '🚀 Automatically create release tags based on files updated in a commit for JS/TS projects 🏷️'
author: 'lr0pb'

branding:
  icon: tag
  color: gray-dark

inputs:
  token:
    description: 'Your token to provide access to GitHub REST API, usually its secrets.GITHUB_TOKEN'
    required: true
  track-file:
    description: 'Path to file used to track updates: some package.json file'
    required: false
    default: 'package.json'
  notes-source:
    description: 'Source type for release notes: changelog | auto'
    required: false
    default: 'changelog'
  notes-file:
    description: 'Path to changelog file used to provide release descriptions'
    required: false
    default: 'CHANGELOG.md'
  tag-pattern:
    description: 'Custom tag pattern for release title'
    required: false
    default: 'v{major}.{minor}.{patch}'

runs:
  using: "node16"
  main: "dist/index.js"
