name: 'Automaticly generate release'
description: '🚀 Generate release based on updated files in commit'
author: 'lr0pb'

branding:
  icon: tag
  color: gray-dark

inputs:
  token:
    description: 'Your GITHUB_TOKEN'
    required: true
  package-path:
    description: 'Path to package.json file'
    required: false
    default: '/package.json'

runs:
  using: "node16"
  main: "dist/index.js"
