name: 'Automaticly generate release'
description: '🚀 Generate release as you update files in your project'
author: 'lr0pb'

branding:
  icon: tag
  color: gray-dark

inputs:
  package-path:
    description: 'Path to package.json file'
    required: false
    default: '/package.json'

runs:
  using: "node16"
  main: "dist/index.js"
